export const env_vars = {
    "MAP_STYLE": process.env.REACT_APP_MAPBOX_STYLE_URL,
    "ACCESS_TOKEN": process.env.REACT_APP_MAPBOX_ACCESS_TOKEN,
    "CHANNEL_ID":process.env.REACT_APP_CHANNEL_ID,
    "INSET_MAP_STYLE":process.env.INSET_MAP_STYLE_URL,
    "INSET_ACCESS":process.env.REACT_MAPBOX_INSET_ACCESS_TOKEN
}